[project]
name = "mastermind-be"
version = "0.1.0"
description = "mastermind-be take-home challenge."
dependencies = [
    "flask",
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"